# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel_odzyskaj_haslo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import crypt

class Ui_MainWindow(object):
    def __init__(self, Window, DataBase):
        super().__init__()
        self.window = Window
        self.db = DataBase

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Odzyskiwanie hasla")
        MainWindow.resize(872, 777)
        MainWindow.setStyleSheet("background-color: rgb(180, 226, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Najlepszy_Kursant = QtWidgets.QLabel(self.centralwidget)
        self.Label_Najlepszy_Kursant.setGeometry(QtCore.QRect(220, 0, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Najlepszy_Kursant.setFont(font)
        self.Label_Najlepszy_Kursant.setAutoFillBackground(False)
        self.Label_Najlepszy_Kursant.setStyleSheet("background-color: rgb(239, 239, 239);\n"
"background-color: rgb(255, 255, 255);")
        self.Label_Najlepszy_Kursant.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Najlepszy_Kursant.setObjectName("Label_Najlepszy_Kursant")
        self.Label_Panel_Kursanta = QtWidgets.QLabel(self.centralwidget)
        self.Label_Panel_Kursanta.setGeometry(QtCore.QRect(220, 40, 501, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Panel_Kursanta.setFont(font)
        self.Label_Panel_Kursanta.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Label_Panel_Kursanta.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Panel_Kursanta.setObjectName("Label_Panel_Kursanta")
        self.Label_Biala_Ramka = QtWidgets.QLabel(self.centralwidget)
        self.Label_Biala_Ramka.setGeometry(QtCore.QRect(220, 90, 501, 621))
        self.Label_Biala_Ramka.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Label_Biala_Ramka.setText("")
        self.Label_Biala_Ramka.setObjectName("Label_Biala_Ramka")
        self.Label_Login = QtWidgets.QLabel(self.centralwidget)
        self.Label_Login.setGeometry(QtCore.QRect(250, 100, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Login.setFont(font)
        self.Label_Login.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Login.setObjectName("Label_Login")
        self.Edit_login = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_login.setGeometry(QtCore.QRect(250, 170, 431, 41))
        self.Edit_login.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.Edit_login.setObjectName("Edit_login")

        self.Edit_login.textChanged.connect(self.pobierz_pytanie)

        self.Label_Pytanie_Pomocnicze = QtWidgets.QLabel(self.centralwidget)
        self.Label_Pytanie_Pomocnicze.setGeometry(QtCore.QRect(250, 220, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Pytanie_Pomocnicze.setFont(font)
        self.Label_Pytanie_Pomocnicze.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Pytanie_Pomocnicze.setObjectName("Label_Pytanie_Pomocnicze")
        
        self.Edit_Pytanie_Pomocnicze = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_Pytanie_Pomocnicze.setGeometry(QtCore.QRect(250, 270, 431, 41))
        self.Edit_Pytanie_Pomocnicze.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.Edit_Pytanie_Pomocnicze.setObjectName("Edit_Pytanie_Pomocnicze")
        self.Edit_Pytanie_Pomocnicze.setReadOnly(True)

        self.Edit_Odp = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_Odp.setGeometry(QtCore.QRect(250, 320, 431, 30))
        self.Edit_Odp.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.Edit_Odp.setObjectName("Edit_Odp")

        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)

        self.Label_Podaj_Haslo1 = QtWidgets.QLabel(self.centralwidget)
        self.Label_Podaj_Haslo1.setGeometry(QtCore.QRect(250, 370, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Podaj_Haslo1.setFont(font)
        self.Label_Podaj_Haslo1.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Podaj_Haslo1.setObjectName("Label_Podaj_Haslo1")
        self.Label_Podaj_Haslo2 = QtWidgets.QLabel(self.centralwidget)
        self.Label_Podaj_Haslo2.setGeometry(QtCore.QRect(250, 470, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Podaj_Haslo2.setFont(font)
        self.Label_Podaj_Haslo2.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Podaj_Haslo2.setObjectName("Label_Podaj_Haslo2")
        self.Edit_Haslo1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_Haslo1.setGeometry(QtCore.QRect(250, 420, 431, 41))
        self.Edit_Haslo1.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.Edit_Haslo1.setObjectName("Edit_Haslo1")
        self.Edit_Haslo1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Edit_Haslo2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_Haslo2.setGeometry(QtCore.QRect(250, 520, 431, 41))
        self.Edit_Haslo2.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.Edit_Haslo2.setObjectName("Edit_Haslo2")
        self.Edit_Haslo2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Label_Informacja_2 = QtWidgets.QLabel(self.centralwidget)
        self.Label_Informacja_2.setGeometry(QtCore.QRect(250, 65, 431, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Informacja_2.setFont(font)
        self.Label_Informacja_2.setStyleSheet("background-color: rgb(255, 255, 255);\n color: rgb(255, 0, 0);")
        self.Label_Informacja_2.setText("")
        self.Label_Informacja_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Informacja_2.setObjectName("Label_Informacja_2")
        self.Btn_zaloguj = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_zaloguj.setGeometry(QtCore.QRect(250, 570, 435, 61))
        self.Btn_Wyjdz = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Wyjdz.setGeometry(QtCore.QRect(250, 640, 435, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_zaloguj.setFont(font)
        self.Btn_zaloguj.setObjectName("Btn_zaloguj")
        self.Btn_zaloguj.clicked.connect(self.zmien_haslo)
        self.Btn_Wyjdz.setFont(font)
        self.Btn_Wyjdz.setObjectName("Btn_Wyjdz")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Btn_Wyjdz.clicked.connect(lambda : self.wyjdz(MainWindow))


    def zmien_haslo(self):
        self.Label_Informacja_2.setStyleSheet("background-color: rgb(255, 255, 255);\n color: rgb(255, 0, 0);")
        login = "'" + self.Edit_login.text() + "'"
        odp = self.Edit_Odp.text()
        odpSHA256 = "'" + crypt.cryptSHA256(odp) + "'"
        haslo1 = self.Edit_Haslo1.text()
        haslo2 = self.Edit_Haslo2.text()
        if haslo1 != haslo2:
            self.Label_Informacja_2.setText("Hasła różnią się!")
            self.Label_Informacja_2.setVisible(1)
            return 1
        elif len(haslo1) < 6:
            self.Label_Informacja_2.setText("Hasła musi mieć minimu 6 znaków!")
            self.Label_Informacja_2.setVisible(1)
            return 1
        querry = "select count(*) from inzynieriaoprogramowania.uzytkownik where login={} and odp_pyt={} ".format(login, odpSHA256)
        q = self.db.querry(querry)
        if q[0][0] == 0:
            self.Label_Informacja_2.setText("Bledne dane!")
            self.Label_Informacja_2.setVisible(1)
            return 1
        hasloSHA =  "'" + crypt.cryptSHA256(haslo1) + "'"
        querry = "update inzynieriaoprogramowania.uzytkownik set haslo={} where login={}".format(hasloSHA, login)
        self.db.querry(querry)
        self.db.commit()
        self.Label_Informacja_2.setStyleSheet("background-color: rgb(255, 255, 255);\n color: rgb(0, 255, 0);")
        self.Label_Informacja_2.setText("Haslo zmienione!")
        self.Label_Informacja_2.setVisible(1)


    def pobierz_pytanie(self):
        login = "'" +self.Edit_login.text() + "'"
        
        querry = "select pytanie_pomocnicze, odp_pyt from inzynieriaoprogramowania.uzytkownik where login={}".format(login)
        dane = self.db.querry(querry)
        if len(dane) != 0:
            self.Edit_Pytanie_Pomocnicze.setText(dane[0][0])

    def wyjdz(self, MainWindow):
        self.Label_Informacja_2.setVisible(0)
        self.window.show()
        MainWindow.close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label_Najlepszy_Kursant.setText(_translate("MainWindow", "NAJLEPSZY KURSANT"))
        self.Label_Panel_Kursanta.setText(_translate("MainWindow", "ODZYSKAJ HASŁO"))
        self.Label_Login.setText(_translate("MainWindow", "Podaj swój login:"))
        self.Label_Pytanie_Pomocnicze.setText(_translate("MainWindow", "Pytanie pomocnicze:"))
        self.Label_Podaj_Haslo1.setText(_translate("MainWindow", "Podaj nowe hasło:"))
        self.Label_Podaj_Haslo2.setText(_translate("MainWindow", "Podaj ponownie nowe hasło:"))
        self.Btn_zaloguj.setText(_translate("MainWindow", "ZATWIERDŹ"))
        self.Btn_Wyjdz.setText(_translate("MainWindow", "WYJDŹ"))
