# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel_uzytkownika.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from panel_egzaminu import Ui_MainWindow2

class Ui_MainWindow(object):
    def __init__(self, MW3, DataBase,UserLogin):
        super().__init__()
        self.MainWindow3 = MW3
        self.db = DataBase
        self.login = UserLogin

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(867, 675)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgb(180, 226, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Najlepszy_Kursant = QtWidgets.QLabel(self.centralwidget)
        self.Label_Najlepszy_Kursant.setGeometry(QtCore.QRect(180, 0, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Najlepszy_Kursant.setFont(font)
        self.Label_Najlepszy_Kursant.setAutoFillBackground(False)
        self.Label_Najlepszy_Kursant.setStyleSheet("background-color: rgb(239, 239, 239);\n"
"background-color: rgb(255, 255, 255);")
        self.Label_Najlepszy_Kursant.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Najlepszy_Kursant.setObjectName("Label_Najlepszy_Kursant")
        self.Label_Panel_Kursanta = QtWidgets.QLabel(self.centralwidget)
        self.Label_Panel_Kursanta.setGeometry(QtCore.QRect(180, 30, 501, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Panel_Kursanta.setFont(font)
        self.Label_Panel_Kursanta.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Label_Panel_Kursanta.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Panel_Kursanta.setObjectName("Label_Panel_Kursanta")
        self.Label_Biala_Ramka = QtWidgets.QLabel(self.centralwidget)
        self.Label_Biala_Ramka.setGeometry(QtCore.QRect(180, 90, 501, 501))
        self.Label_Biala_Ramka.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Label_Biala_Ramka.setText("")
        self.Label_Biala_Ramka.setObjectName("Label_Biala_Ramka")
        self.Btn_Nauka_przepisow = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Nauka_przepisow.setGeometry(QtCore.QRect(240, 120, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_Nauka_przepisow.setFont(font)
        self.Btn_Nauka_przepisow.setObjectName("Btn_Nauka_przepisow")
        self.Btn_Nauka_czynnosci = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Nauka_czynnosci.setGeometry(QtCore.QRect(240, 170, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_Nauka_czynnosci.setFont(font)
        self.Btn_Nauka_czynnosci.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.Btn_Nauka_czynnosci.setObjectName("Btn_Nauka_czynnosci")
        self.Btn_Wybor_Trasy = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Wybor_Trasy.setGeometry(QtCore.QRect(240, 270, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_Wybor_Trasy.setFont(font)
        self.Btn_Wybor_Trasy.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.Btn_Wybor_Trasy.setObjectName("Btn_Wybor_Trasy")
        self.Btn_Statystyki = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Statystyki.setGeometry(QtCore.QRect(240, 220, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_Statystyki.setFont(font)
        self.Btn_Statystyki.setObjectName("Btn_Statystyki")
        self.Btn_Przeglad_Testow = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Przeglad_Testow.setGeometry(QtCore.QRect(240, 420, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_Przeglad_Testow.setFont(font)
        self.Btn_Przeglad_Testow.setObjectName("Btn_Przeglad_Testow")
        self.Btn_Symulacja = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Symulacja.setGeometry(QtCore.QRect(240, 370, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_Symulacja.setFont(font)
        self.Btn_Symulacja.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.Btn_Symulacja.setObjectName("Btn_Symulacja")
        self.Btn_Podrecznik = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Podrecznik.setGeometry(QtCore.QRect(240, 470, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_Podrecznik.setFont(font)
        self.Btn_Podrecznik.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.Btn_Podrecznik.setObjectName("Btn_Podrecznik")
        self.Btn_Egzamin = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Egzamin.setGeometry(QtCore.QRect(240, 320, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_Egzamin.setFont(font)
        self.Btn_Egzamin.setObjectName("Btn_Egzamin")
        self.Btn_Wyloguj = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Wyloguj.setGeometry(QtCore.QRect(360, 520, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Wyloguj.setFont(font)
        self.Btn_Wyloguj.setObjectName("Btn_Wyloguj")
        self.Label_Zalogowany_Jako = QtWidgets.QLabel(self.centralwidget)
        self.Label_Zalogowany_Jako.setGeometry(QtCore.QRect(0, 0, 101, 21))
        self.Label_Zalogowany_Jako.setObjectName("Label_Zalogowany_Jako")
        self.Label_Uzytkownik = QtWidgets.QLabel(self.centralwidget)
        self.Label_Uzytkownik.setGeometry(QtCore.QRect(20, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Uzytkownik.setFont(font)
        self.Label_Uzytkownik.setObjectName("Label_Uzytkownik")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Btn_Egzamin.clicked.connect(lambda: self.p_egzaminu(MainWindow))
        self.Btn_Wyloguj.clicked.connect(lambda: self.btn_wyloguj(MainWindow))

    def btn_wyloguj(self, MainWindow):
        querry = "update inzynieriaoprogramowania.uzytkownik set czy_zalogowany=0 where login={}".format(self.login)
        self.db.querry(querry)
        self.db.commit()

        self.MainWindow3.show()
        MainWindow.close()

    def p_egzaminu(self,  MainWindow):
        self.MainWindow2 = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow2(MainWindow)
        self.ui.setupUi(self.MainWindow2)
        self.MainWindow2.show()
        MainWindow.hide()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Panel Uzytkownika"))
        self.Label_Najlepszy_Kursant.setText(_translate("MainWindow", "NAJLEPSZY KURSANT"))
        self.Label_Panel_Kursanta.setText(_translate("MainWindow", "PANEL KURSANTA"))
        self.Btn_Nauka_przepisow.setText(_translate("MainWindow", "Nauka przepisów drogowych"))
        self.Btn_Nauka_czynnosci.setText(_translate("MainWindow", "Nauka czynności kontrolno - obsługowych"))
        self.Btn_Wybor_Trasy.setText(_translate("MainWindow", "Wybór trasy"))
        self.Btn_Statystyki.setText(_translate("MainWindow", "Statystyki"))
        self.Btn_Przeglad_Testow.setText(_translate("MainWindow", "Przegląd testów"))
        self.Btn_Symulacja.setText(_translate("MainWindow", "Symulacja"))
        self.Btn_Podrecznik.setText(_translate("MainWindow", "Podręcznik Kursanta"))
        self.Btn_Egzamin.setText(_translate("MainWindow", "Egzamin próbny"))
        self.Btn_Wyloguj.setText(_translate("MainWindow", "Wyloguj"))
        self.Label_Zalogowany_Jako.setText(_translate("MainWindow", "Zalogowany jako:"))

        querry = self.db.querry("select imie, nazwisko from inzynieriaoprogramowania.uzytkownik where login={}".format(self.login))
        imie = querry[0][0]
        nazwisko = querry[0][1]
        self.Label_Uzytkownik.setText(_translate("MainWindow", imie+" "+nazwisko))

