# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel_logowania.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from panel_uzytkownika import Ui_MainWindow
from panel_odzyskaj_haslo import Ui_MainWindow as Haslo
from database import DataBase
import crypt

class Ui_MainWindow3(object):
    def __init__(self):
        super().__init__()
        self.db = DataBase()

    def setupUi(self, MainWindow3):
        MainWindow3.setObjectName("MainWindow")
        MainWindow3.resize(872, 674)
        MainWindow3.setStyleSheet("background-color: rgb(180, 226, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow3)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Najlepszy_Kursant = QtWidgets.QLabel(self.centralwidget)
        self.Label_Najlepszy_Kursant.setGeometry(QtCore.QRect(210, 0, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Najlepszy_Kursant.setFont(font)
        self.Label_Najlepszy_Kursant.setAutoFillBackground(False)
        self.Label_Najlepszy_Kursant.setStyleSheet("background-color: rgb(239, 239, 239);\n"
"background-color: rgb(255, 255, 255);")
        self.Label_Najlepszy_Kursant.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Najlepszy_Kursant.setObjectName("Label_Najlepszy_Kursant")
        self.Label_Panel_Kursanta = QtWidgets.QLabel(self.centralwidget)
        self.Label_Panel_Kursanta.setGeometry(QtCore.QRect(210, 40, 501, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Panel_Kursanta.setFont(font)
        self.Label_Panel_Kursanta.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Label_Panel_Kursanta.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Panel_Kursanta.setObjectName("Label_Panel_Kursanta")
        self.Label_Biala_Ramka = QtWidgets.QLabel(self.centralwidget)
        self.Label_Biala_Ramka.setGeometry(QtCore.QRect(210, 110, 501, 501))
        self.Label_Biala_Ramka.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Label_Biala_Ramka.setText("")
        self.Label_Biala_Ramka.setObjectName("Label_Biala_Ramka")

        self.Label_Bledne_Haslo = QtWidgets.QLabel(self.centralwidget)
        self.Label_Bledne_Haslo.setGeometry(QtCore.QRect(420, 270, 180,50))
        self.Label_Bledne_Haslo.setStyleSheet("background-color: rgb(255, 255, 255);\n color: rgb(255, 0, 0);")
        self.Label_Bledne_Haslo.setText("Błędny login lub hasło!")
        self.Label_Bledne_Haslo.setObjectName("Label_Bledne_Haslo")
        self.Label_Bledne_Haslo.setVisible(False)


        self.Label_Haslo = QtWidgets.QLabel(self.centralwidget)
        self.Label_Haslo.setGeometry(QtCore.QRect(250, 320, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Haslo.setFont(font)
        self.Label_Haslo.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Haslo.setObjectName("Label_Haslo")

        self.Edit_login = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_login.setGeometry(QtCore.QRect(250, 190, 431, 87))
        self.Edit_login.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.Edit_login.setObjectName("Edit_login")

        self.textEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(250, 390, 431, 87))
        self.textEdit_2.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)

        self.Label_Login = QtWidgets.QLabel(self.centralwidget)
        self.Label_Login.setGeometry(QtCore.QRect(250, 120, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Login.setFont(font)
        self.Label_Login.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Login.setObjectName("Label_Login")
        self.Btn_Zapom_haslo = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Zapom_haslo.setGeometry(QtCore.QRect(250, 560, 431, 28))
        self.Btn_Zapom_haslo.setStyleSheet("background-color: rgb(238, 151, 156);")
        self.Btn_Zapom_haslo.setObjectName("Btn_Zapom_haslo")
        self.Btn_zaloguj = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_zaloguj.setGeometry(QtCore.QRect(250, 490, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_zaloguj.setFont(font)
        self.Btn_zaloguj.setObjectName("Btn_zaloguj")
        MainWindow3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 26))
        self.menubar.setObjectName("menubar")
        MainWindow3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow3)
        self.statusbar.setObjectName("statusbar")
        MainWindow3.setStatusBar(self.statusbar)
        self.Btn_zaloguj.clicked.connect(self.zaloguj)
        self.Btn_Zapom_haslo.clicked.connect(self.zapomnialem_hasla)

        self.retranslateUi(MainWindow3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow3)

       
    def zapomnialem_hasla(self):
        self.Label_Bledne_Haslo.setVisible(False)
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Haslo(MainWindow3, self.db)
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()
        MainWindow3.hide()
        
    def zaloguj(self):
        self.db.commit()
        haslo = self.textEdit_2.text()
        login = "'" + self.Edit_login.text() + "'"
        hasloSHA256 = "'" + crypt.cryptSHA256(haslo) + "'"
        self.textEdit_2.setText("")
        self.Edit_login.setText("")

        querry="select * from inzynieriaoprogramowania.uzytkownik where login={} and haslo={}".format(login, hasloSHA256)
        querr = self.db.querry(querry)
        if len(querr) != 1:
            self.Label_Bledne_Haslo.setText("Błędny login lub hasło!")
            self.Label_Bledne_Haslo.setVisible(True)
            return 0
        elif querr[0][len(querr[0])-1] == 1:
            self.Label_Bledne_Haslo.setText("Użytkownik jest już zalogowany!")
            self.Label_Bledne_Haslo.setVisible(True)
            return 0
        querry = "update inzynieriaoprogramowania.uzytkownik set czy_zalogowany=1 where login={}".format(login)
        self.db.querry(querry)
        self.db.commit()

        self.Label_Bledne_Haslo.setVisible(False)
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow(MainWindow3, self.db, login)
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()
        MainWindow3.hide()

    def retranslateUi(self, MainWindow3):
        _translate = QtCore.QCoreApplication.translate
        MainWindow3.setWindowTitle(_translate("MainWindow", "Panel Logowania"))
        self.Label_Najlepszy_Kursant.setText(_translate("MainWindow", "NAJLEPSZY KURSANT"))
        self.Label_Panel_Kursanta.setText(_translate("MainWindow", "PANEL LOGOWANIA"))
        self.Label_Haslo.setText(_translate("MainWindow", "Podaj swoje hasło:"))
        self.Label_Login.setText(_translate("MainWindow", "Podaj swój login:"))
        self.Btn_Zapom_haslo.setText(_translate("MainWindow", "Zapomniałem hasła"))
        self.Btn_zaloguj.setText(_translate("MainWindow", "ZALOGUJ SIĘ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow3 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow3()
    ui.setupUi(MainWindow3)
    MainWindow3.show()
    sys.exit(app.exec_())
